// Modulo Actividades
export const GET_HORARIOS           = 'CONSULTA_HORARIO';

export const GET_ACTIVIDADES        = 'CONSULTA_ACTIVIDADES';
export const POST_ACTIVIDAD         = 'AGREGAR_ACTIVIDAD';
export const UPDATE_ACTIVIDAD       = 'ACTUALIZAR_ACTIVIDAD';
export const DELETE_ACTIVIDAD       = 'ELIMINAR_ACTIVIDAD';

export const GET_PERSONALIZADOS     = 'CONSULTA_PERSONALIZADOS';
export const POST_PERSONALIZADO     = 'AGREGAR_PERSONALIZADO';
export const UPDATE_PERSONALIZADO   = 'ACTUALIZAR_PERSONALIZADO';
export const DELETE_PERSONALIZADO   = 'ELIMINAR_PERSONALIZADO';

export const GET_VOLUNTARIOS        = 'CONSULTA_VOLUNTARIOS';
export const POST_VOLUNTARIO        = 'AGREGAR_VOLUNTARIO';
export const UPDATE_VOLUNTARIO      = 'ACTUALIZAR_VOLUNTARIO';
export const DELETE_VOLUNTARIO      = 'ELIMINAR_VOLUNTARIO';

export const GET_SOLICITUDES        = 'CONSULTA_SOLICITUDES';
export const POST_SOLICITUDES       = 'AGREGAR_SOLICITUD';
export const UPDATE_SOLICITUDES     = 'ACTUALIZAR_SOLICITUD';
export const ACCEPT_SOLICITUDES     = 'ACEPTAR_SOLICITUD';
export const REJECT_SOLICITUDES     = 'RECHAZAR_SOLICITUD';

export const GET_ANIMALES           = 'CONSULTA_ANIMALES';
export const POST_ANIMAL            = 'AGREGAR_ANIMAL';
export const UPDATE_ANIMAL          = 'ACTUALIZAR_ANIMAL';
export const DELETE_ANIMAL          = 'ELIMINAR_ANIMAL';

export const GET_USUARIOS           = 'CONSULTAR_USUARIO_LOGIN';